value instead of valueCoding #225
hl7ch/ch-core pull request #229
Opened 2023-06-21 14:58 UTC by oliveregger

#225

2023-06-22 06:01 UTC, ziegm approved these changes

2023-06-22 06:25 UTC, ziegm requested changes
There are new errors now in the QA:
http://build.fhir.org/ig/hl7ch/ch-core/branches/oe_fhirpath/qa.html

2023-06-26 10:22 UTC, oliveregger commented
@ziegm: could you recheck please, should be fixed now http://build.fhir.org/ig/hl7ch/ch-core/branches/oe_fhirpath/qa.html

2023-06-27 05:50 UTC, ziegm approved these changes

2023-06-27 18:41 UTC, merged